### ISSUE TITLE
Dependency on IPython not declared in requirements

### ISSUE THREAD

**Issue by tschm** [ranaroussi/quantstats#295]
IPython is used in reports to generate html files...
Please add the dependency

**Comment by sawaca96** [comment]
any update?

**Comment by brent-ridian** [comment]
**This is indeed a bug**.

I just got burned by this too.

I created a new venv for my project yesterday in order to use quantstats functions like cagr, sharpe, sortino, etc.

But when I tried to use them in my code with that new venv, I get this error:

```
Traceback (most recent call last):
  File "C:\brilly\virtualenvs\quant-venv\lib\site-packages\quantstats\reports.py", line 33, in <module>
    from IPython.display import display as iDisplay, HTML as iHTML
ModuleNotFoundError: No module named 'IPython'
```

If you look at reports.py (which my code does not directly use--it must be some kind of transitive dependency), the offending code is this section:

```
try:
    from IPython.display import display as iDisplay, HTML as iHTML
except ImportError:
    from IPython.core.display import display as iDisplay, HTML as iHTML
```

So, the fix will either be to add iPython as a dependency in requirements.txt (likely the easiest route) or else code like reports.py above will need to add an except clause for ModuleNotFoundError and have some kind of fall back for display and HTML.

**Comment by jjohnson** [comment]
Bug confirmed in latest:

### Steps to reproduce

```python
import quantstats as qs
```

### Actual behavior

```python
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.13/site-packages/quantstats/reports.py", line 33, in <module>
    from IPython.display import display as iDisplay, HTML as iHTML
ModuleNotFoundError: No module named 'IPython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import quantstats as qs
  File "/home/vscode/.local/lib/python3.13/site-packages/quantstats/__init__.py", line 26, in <module>
    from . import stats, utils, plots, reports
  File "/home/vscode/.local/lib/python3.13/site-packages/quantstats/reports.py", line 35, in <module>
    from IPython.core.display import display as iDisplay, HTML as iHTML
ModuleNotFoundError: No module named 'IPython'
```

### System configuration

```python
$ pip show quantstats
Name: QuantStats
Version: 0.0.63
```

Maybe this is just waiting for a patch to be opened?

**Comment by tschm** [comment]
I have added a deptry based GitHub workflow to identify obsolete and missing dependencies

**Comment by ranaroussi** [comment]
Closing this issue as it's older than 2025. The comprehensive dependency handling improvements in version 0.0.64 should address IPython dependency issues. If you're still experiencing problems, please create a new issue with the latest version.
