### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'product'

### ISSUE THREAD

**Issue by larytet** [ranaroussi/quantstats#361]
I am working with a Python virtual environment
```
$ pip list | grep numpy
numpy                     2.0.1
```
My code 

```Python 
# pip3 install virtualenv
# python3 -m venv myenv
# ~/.local/bin/virtualenv myenv
# source myenv/bin/activate
# pip3 install ipython
# pip3 install -r requirements.txt
# pip3 install notebook
# ~/.local/bin/jupyter-notebook
import pandas as pd
import quantstats as qs

# Manually set the filename
filename = 'BTCLV TRADES.csv'

# Extend pandas functionality with metrics, etc.
qs.extend_pandas()

# Read the CSV file into a DataFrame
trades = pd.read_csv(filename, parse_dates=['End Time', 'Next Start Time'])

# Set the 'End Time' as the index
trades.set_index('End Time', inplace=True)

# Resample to daily frequency and forward-fill missing values
daily_equity = trades['Balance'].resample('D').ffill()

# Calculate daily returns
daily_returns = daily_equity.pct_change().dropna()

# Calculate the Sharpe ratio
sharpe_ratio = qs.stats.sharpe(daily_returns)

# Print the Sharpe ratio
print(f'Sharpe Ratio: {sharpe_ratio}')

# Alternatively, using the extend_pandas() functionality
print(daily_returns.sharpe())
qs.plots.snapshot(daily_returns, title='BTC Performance', show=True)
report = qs.reports.html(daily_returns, title='BTC Trading Performance Report')

# Save the report to an HTML file
with open('btc_trading_performance_report.html', 'w') as f:
    f.write(report)

```

```
/home/arkady/quantstats/quantstats/_plotting/wrappers.py:257: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  _plt.show(block=False)
Traceback (most recent call last):
  File "/home/arkady/quantstats/test.py", line 39, in <module>
    qs.reports.html(daily_returns, title='BTC Trading Performance Report', output='btc_trading_performance_report.html')
  File "/home/arkady/quantstats/quantstats/reports.py", line 124, in html
    mtrx = metrics(
  File "/home/arkady/quantstats/quantstats/reports.py", line 933, in metrics
    _stats.expected_return(df, compounded=compounded, prepare_returns=False) * pct
  File "/home/arkady/quantstats/quantstats/stats.py", line 96, in expected_return
    return _np.product(1 + returns) ** (1 / len(returns)) - 1
  File "/home/arkady/quantstats/myenv/lib/python3.10/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'product'
```

Should the code use `prod` instead of `product`?

**Comment by QlDoors** [comment]
Yes. You can find 'product = prod' in the file 'pandas/core/frame.py'.

**Comment by larytet** [comment]
I just forked and patched the `quantstats` . I don't know why the code fails in my settings

**Comment by iDevBrandon** [comment]
How did you solve this issue?

**Comment by larytet** [comment]
> How did you solve this issue?

https://github.com/larytet-py/quantstats/tree/patched
https://github.com/ranaroussi/quantstats/commit/9ffccac0cf1f9d51033fa834c66b06a8cab223e9
