### ISSUE TITLE
stats.sharpe raise error when input is pd.Series.

### ISSUE THREAD

**Issue by g199209** [ranaroussi/quantstats#384]
commit [8ce8784](https://github.com/ranaroussi/quantstats/commit/8ce878440794a42a7eeb16cecdf7bab23285d099#diff-2f6178806a46aa5998b8bcfc18a87a97269f8a3acd562791a20b793d94589def) introduce this bug.

This patch adds a lot of `data = data.tz_localize(None)` in `utils.py`, for example in `_prepare_prices`.

But if input data is pd.Series, not Dataframe, `data.tz_localize` is wrong.

```
>>> data = pd.Series([0.000000, 0.000008])
>>> data
0    0.000000
1    0.000008
dtype: float64
>>> data.tz_localize(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mingfei/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 11725, in tz_localize
    ax = _tz_localize(ax, tz, ambiguous, nonexistent)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingfei/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 11708, in _tz_localize
    raise TypeError(
TypeError: index is not a valid DatetimeIndex or PeriodIndex
```

**Comment by ranaroussi** [comment]
Closing this issue as it's older than 2025. The comprehensive input validation improvements in version 0.0.64 should address pandas Series handling issues. If you're still experiencing problems, please create a new issue with the latest version.
