### ISSUE TITLE
Error:  ValueError: operands could not be broadcast together with shapes (12,) (11,) 

### ISSUE THREAD

**Issue by alexrios22** [ranaroussi/quantstats#50]
I am running the following backtesting with monthly returns:

```
# =============================================================================
# Backtesting strategy - I : Monthly portfolio rebalancing
# Author : Mayank Rasu

# Please report bug/issues in the Q&A section
# =============================================================================

import numpy as np
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as pdr
import datetime
import copy
import quantstats as qs

# Download historical data (monthly) for DJI constituent stocks
tickers = ["MMM","AXP","T","BA","CAT","CVX","CSCO","KO", "XOM","GE","GS","HD",
           "IBM","INTC","JNJ","JPM","MCD","MRK","MSFT","NKE","PFE","PG","TRV",
           "UNH","VZ","V","WMT","DIS","SPY","QQQ","TLT","LQD","GLD","SLV","IEI","AAPL"]

ohlc_mon = {} # directory with ohlc value for each stock            
attempt = 0 # initializing passthrough variable
drop = [] # initializing list to store tickers whose close price was successfully extracted
while len(tickers) != 0 and attempt <= 5:
    tickers = [j for j in tickers if j not in drop] # removing stocks whose data has been extracted from the ticker list
    for i in range(len(tickers)):
        try:
            ohlc_mon[tickers[i]] = pdr.get_data_yahoo(tickers[i],datetime.date.today()-datetime.timedelta(5500),datetime.date.today(),interval='m')
            ohlc_mon[tickers[i]].dropna(inplace = True)
            drop.append(tickers[i])       
        except:
            print(tickers[i]," :failed to fetch data...retrying")
            continue
    attempt+=1
 
tickers = ohlc_mon.keys() # redefine tickers variable after removing any tickers with corrupted data

################################Backtesting####################################

# calculating monthly return for each stock and consolidating return info by stock in a separate dataframe
ohlc_dict = copy.deepcopy(ohlc_mon)
return_df = pd.DataFrame()
for ticker in tickers:
    print("calculating monthly return for ",ticker)
    ohlc_dict[ticker]["mon_ret"] = ohlc_dict[ticker]["Adj Close"].pct_change()
    return_df[ticker] = ohlc_dict[ticker]["mon_ret"]

# function to calculate portfolio return iteratively
def pflio(DF,m,x):
    """Returns cumulative portfolio return
    DF = dataframe with monthly return info for all stocks
    m = number of stock in the portfolio
    x = number of underperforming stocks to be removed from portfolio monthly"""
    df = DF.copy()
    
    portfolio = []
    monthly_ret = [0]
    for i in range(1,len(df)):
        if len(portfolio) > 0:
            monthly_ret.append(df[portfolio].iloc[i,:].mean())
            bad_stocks = df[portfolio].iloc[i,:].sort_values(ascending=True)[:x].index.values.tolist()
            portfolio = [t for t in portfolio if t not in bad_stocks]
        fill = m - len(portfolio)
        new_picks = df.iloc[i,:].sort_values(ascending=False)[:fill].index.values.tolist()
        portfolio = portfolio + new_picks
        print(portfolio)
        
    monthly_ret_df = pd.DataFrame(np.array(monthly_ret),columns=["mon_ret"])
    
    return monthly_ret_df

Strategy = pflio(return_df,6,3)
Strategy["Date"] = return_df[1:].index.values
Strategy.set_index("Date", inplace = True)

#calculating KPIs for Index buy and hold strategy over the same period
SP500 = pdr.get_data_yahoo("^GSPC",datetime.date.today()-datetime.timedelta(5500),datetime.date.today(),interval='m')
SP500["mon_ret"] =SP500["Adj Close"].pct_change()

#len(DJI["mon_ret"][1:])

qs.reports.html(Strategy["mon_ret"], SP500["mon_ret"][1:], output='report2.html', title = "Monthly portfolio rebalancing")
```

But when requesting the report it throws me the following error:

```
File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\nanops.py", line 127, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\nanops.py", line 479, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))

  File "C:\Users\Alexrios22\AppData\Roaming\Python\Python38\site-packages\numpy\core\_methods.py", line 38, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)

ValueError: operands could not be broadcast together with shapes (12,) (11,) 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\nanops.py", line 130, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\nanops.py", line 479, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))

  File "C:\Users\Alexrios22\AppData\Roaming\Python\Python38\site-packages\numpy\core\_methods.py", line 38, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)

ValueError: operands could not be broadcast together with shapes (12,) (11,) 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Alexrios22\Downloads\Trading\Curso Algorithmic Trading And Quantitative Analysis Using Python\Market Map\Rebalancing\Rebalancing.py", line 82, in <module>
    qs.reports.html(Strategy["mon_ret"], SP500["mon_ret"][1:], output='report2.html', title = "Monthly portfolio rebalancing")

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\quantstats\reports.py", line 121, in html
    _plots.yearly_returns(returns, benchmark, grayscale=grayscale,

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\quantstats\_plotting\wrappers.py", line 362, in yearly_returns
    hline=returns.mean(),

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 10945, in stat_func
    return self._reduce(f, name, axis=axis, skipna=skipna,

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\series.py", line 3626, in _reduce
    return op(delegate, skipna=skipna, **kwds)

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\nanops.py", line 76, in _f
    return f(*args, **kwargs)

  File "C:\Users\Alexrios22\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\nanops.py", line 138, in f
    raise TypeError(e)

TypeError: operands could not be broadcast together with shapes (12,) (11,) 
```

I had already run it before, and it hadn't given me that error, but now it does.

**Comment by christian-storm** [comment]
I've run into this sort of error too and it has also been sporadic.  After some digging, it seems that if the first year has only one data point then the code in quanstats._plotting.wrappers.yearly_returns:

    returns = _utils._prepare_returns(returns).resample('A')
    if compounded:
        returns = returns.apply(_stats.compsum)  <-----
    else:
        returns = returns.apply(_df.cumsum)  <-----
    returns = returns.resample('A').last()

returns a Series with values that range from scalars to arrays that don't have the same shape (leap year, trading day, etc. differences) instead of just scalars.  The compsum or cumsum seems to group by day.  Perhaps the sampler samples along the wrong axis?  I wanted to suggest a fix to @ranaroussi but I couldn't figure it out.

This code reproduces the problem:

    import pandas as pd
    import pandas_datareader.data as pdr
    import quantstats as qs
    
    SP500 = pdr.get_data_yahoo("^GSPC", pd.to_datetime('2009-12-31'), pd.to_datetime('2020-01-02'), interval='d')
    SP500["mon_ret"] =SP500["Adj Close"].pct_change()
    
    qs.reports.html(SP500["mon_ret"], output='report2.html', title = "Monthly portfolio rebalancing")

A frustrating one because it can crop up anytime when a user-specified date range is just right (one day/month/...) in a year.
