### ISSUE TITLE
pip install of 0.0.28 fails on not finding requirements.txt

### ISSUE THREAD

**Issue by kartiksubbarao** [ranaroussi/quantstats#77]
pip install of 0.0.28 fails because it can't find requirements.txt:

```
Collecting quantstats
  Downloading QuantStats-0.0.28.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-14s2qa3d/quantstats_ae2e00885b714c9bb0314edf90054ca9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-14s2qa3d/quantstats_ae2e00885b714c9bb0314edf90054ca9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ea65ulhr
         cwd: /tmp/pip-install-14s2qa3d/quantstats_ae2e00885b714c9bb0314edf90054ca9/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-14s2qa3d/quantstats_ae2e00885b714c9bb0314edf90054ca9/setup.py", line 30, in <module>
        with open(req_file, encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
```

**Comment by cryptocoinserver** [comment]
Can confirm this issue.

**Comment by ranaroussi** [comment]
Fixed
